version: "3.9"
services:
  # image micro-auth
  micro_auth:
    build:
      args:
        - user=fhariano
        - uid=1000
      context: ./
      dockerfile: dockerfile
    environment: 
      TZ: "${TZ:-America/Sao_Paulo}"
    image: laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - redis_auth
      - queue
    networks:
      - microauth
  
  # nginx
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8090:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - microauth

  # mysql micro_auth
  db_micro_auth:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      TZ: "${TZ:-America/Sao_Paulo}"
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    ports: 
      - 3340:3306
    networks:
      - microauth

  # queue micro 01
  queue:
    build:
      args:
        - user=fhariano
        - uid=1000
      context: ./
      dockerfile: dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    command: "php artisan queue:work"
    volumes:
      - ./:/var/www
    depends_on: 
      - redis_auth
    networks:
      - microauth

  # redis
  redis_auth:
    image: redis:latest
    networks:
      - microauth

networks:
  microauth:
    driver: bridge